steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t',
          'gcr.io/python_dice/38_pytest',
          '.',
          '-f',
          'continuous_integration/38_pytest_ci.dockerfile' ]
  timeout: 40m
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t',
         'gcr.io/python_dice/37_pytest',
         '.',
         '-f',
         'continuous_integration/37_pytest.dockerfile']
  timeout: 20m
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
         '-t',
         'gcr.io/python_dice/36_pytest',
         '.',
         '-f',
         'continuous_integration/36_pytest.dockerfile' ]
  timeout: 20
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
         '-t',
         'gcr.io/python_dice/test_pip_install',
         '.',
         '-f',
         'continuous_integration/test_pip_install.dockerfile' ]
  timeout: 20m
  waitFor: ['-']
timeout: 100m